"""Pydantic request/response models for the API.

These types do two jobs:

  1. SHAPE: define what a valid request looks like (JSON schema is auto-
     generated by FastAPI, becomes the /docs page).
  2. BOUNDS: enforce that callers stay inside the surrogate's training
     region. A trained NN is only meaningful WITHIN its training region —
     outside, it extrapolates and returns garbage. Rejecting out-of-bounds
     input at the API boundary is non-negotiable for any real risk system.

Bound constants come from `app.config` so this file imports numbers, not
duplicates them.

NB: this file deliberately does NOT use `from __future__ import annotations`.
Pydantic v2 has had subtle edge cases with stringified annotations (model
rebuild for forward refs, Annotated[...] resolution). Keep model files
concrete-annotated until/unless you need lazy eval.
"""
from datetime import datetime
from typing import Self

import numpy as np
from pydantic import BaseModel, Field, field_validator, model_validator

from app.config import (
    F_HI,
    F_LO,
    LMM_PARAM_HI,
    LMM_PARAM_LO,
    LMM_PARAM_NAMES,
    LOG_M_HI,
    LOG_M_LO,
    T_HI,
    T_LO,
)


# =============================================================================
# Instruments + params (with bounds validation)
# =============================================================================
class Instrument(BaseModel):
    """A (T, K, F) tuple — caplet/swaption coordinates."""

    T: float = Field(..., description="Years to expiry.", examples=[1.0])
    K: float = Field(..., description="Strike.", examples=[0.030])
    F: float = Field(..., description="Forward rate.", examples=[0.035])

    # ------------------------------------------------------------------
    # TODO A — implement bounds validation.
    # WHY: the surrogate was trained for T in [T_LO, T_HI], F in [F_LO, F_HI],
    # and log(K/F) in [LOG_M_LO, LOG_M_HI]. Outside this box, NN predictions
    # are unreliable. Reject the request rather than silently return bad IVs.
    #
    # PATTERN with pydantic v2 — two @field_validator + one @model_validator:
    #
    #     @field_validator("T")
    #     @classmethod
    #     def _check_T(cls, v: float) -> float:
    #         if not (T_LO <= v <= T_HI):
    #             raise ValueError(f"T={v} outside training range [{T_LO}, {T_HI}]")
    #         return v
    #
    #     @field_validator("F")
    #     @classmethod
    #     def _check_F(cls, v: float) -> float:
    #         if not (F_LO <= v <= F_HI):
    #             raise ValueError(f"F={v} outside training range [{F_LO}, {F_HI}]")
    #         return v
    #
    #     # K is bounds-checked through log(K/F) — needs BOTH F and K, so use
    #     # @model_validator(mode="after") which runs after field validation.
    #     @model_validator(mode="after")
    #     def _check_log_moneyness(self) -> Self:
    #         lm = float(np.log(self.K / self.F))
    #         if not (LOG_M_LO <= lm <= LOG_M_HI):
    #             raise ValueError(
    #                 f"log(K/F)={lm:.3f} outside [{LOG_M_LO}, {LOG_M_HI}]"
    #             )
    #         return self
    # ------------------------------------------------------------------
    @field_validator("T")
    @classmethod
    def _check_T(cls, value: float) -> float:
        if not (T_LO <= value <= T_HI):
            raise ValueError(f"T={value} outside training range [{T_LO}, {T_HI}]")
        return value
    
    @field_validator("F")
    @classmethod
    def _check_F(cls, value: float) -> float:
        if not (F_LO <= value <= F_HI):
            raise ValueError(f"F={value} outside training range [{F_LO}, {F_HI}]")
        return value
    
    @model_validator(mode="after")
    def _check_moneyness(self) -> Self:
        lm = float(np.log(self.K / self.F))
        if not (LOG_M_LO <= lm <= LOG_M_HI):
            raise ValueError(f"log(K/F)={lm:.3f} outside [{LOG_M_LO}, {LOG_M_HI}]")
        return self


class Params(BaseModel):
    """LMM params (sig_a, sig_c, sabr_alpha, rho_inf). Order matches LMM_PARAM_NAMES."""

    sig_a:      float = Field(..., examples=[0.18])
    sig_c:      float = Field(..., examples=[0.40])
    sabr_alpha: float = Field(..., examples=[0.015])
    rho_inf:    float = Field(..., examples=[0.30])

    # ------------------------------------------------------------------
    # TODO B — implement bounds validation.
    # WHY: same reasoning as Instrument. The training samples each param
    # uniformly in its [LO, HI] slot, so the NN is only trusted in that
    # box. Reject outside.
    #
    # PATTERN — one @model_validator that checks all four at once:
    #
    #     @model_validator(mode="after")
    #     def _check_bounds(self) -> Self:
    #         vec = np.array(
    #             [self.sig_a, self.sig_c, self.sabr_alpha, self.rho_inf]
    #         )
    #         for name, val, lo, hi in zip(
    #             LMM_PARAM_NAMES, vec, LMM_PARAM_LO, LMM_PARAM_HI
    #         ):
    #             if not (lo <= val <= hi):
    #                 raise ValueError(f"{name}={val} outside [{lo}, {hi}]")
    #         return self
    # ------------------------------------------------------------------

    def as_array(self) -> np.ndarray:
        """Convenience for passing to nn_iv (which wants a numpy array)."""
        return np.array(
            [self.sig_a, self.sig_c, self.sabr_alpha, self.rho_inf],
            dtype=np.float64,
        )
        
    @model_validator(mode="after")
    def _check_bounds(self) -> Self:
        vec = np.array([self.sig_a, self.sig_c, self.sabr_alpha, self.rho_inf])
        for name, val, lo, hi in zip(LMM_PARAM_NAMES, vec, LMM_PARAM_LO, LMM_PARAM_HI):
            if not (lo <= val <= hi):
                raise ValueError(f"{name}={val} outside [{lo}, {hi}]")
        return self


# =============================================================================
# /calibrate
# =============================================================================
class CalibrateRequest(BaseModel):
    instruments: list[Instrument] = Field(..., min_length=1)
    market_ivs:  list[float]      = Field(..., min_length=1, examples=[[0.3591, 0.3657]])
    x0:          list[float] | None = None

    # ------------------------------------------------------------------
    # TODO C — assert len(instruments) == len(market_ivs).
    # WHY: a mismatched length is the single most common caller bug.
    # Catch it at the schema, not deep inside the service.
    #
    # PATTERN:
    #
    #     @model_validator(mode="after")
    #     def _check_length_match(self) -> Self:
    #         if len(self.instruments) != len(self.market_ivs):
    #             raise ValueError(
    #                 f"len(instruments)={len(self.instruments)} != "
    #                 f"len(market_ivs)={len(self.market_ivs)}"
    #             )
    #         return self
    # ------------------------------------------------------------------
    @model_validator(mode="after")
    def _check_length_match(self) -> Self:
        if len(self.instruments) != len(self.market_ivs):
            raise ValueError(
                f"len(instruments)={len(self.instruments)} != "
                f"len(market_ivs)={len(self.market_ivs)}"
            )
        return self
    
    @model_validator(mode="after")
    def _check_x0(self) -> Self:
        if self.x0 is None:
            return self
        if len(self.x0) != len(LMM_PARAM_NAMES):
            raise ValueError(f"len(x0)={len(self.x0)} != {len(LMM_PARAM_NAMES)}")
        for name, val, lo, hi in zip(
            LMM_PARAM_NAMES, self.x0, LMM_PARAM_LO, LMM_PARAM_HI
        ):
            if not (lo <= val <= hi):
                raise ValueError(f"{name}={val} outside [{lo}, {hi}]")
        return self
    

class VerifyRow(BaseModel):
    instrument:   str
    market:       float
    nn:           float
    mc:           float
    calib_bp:     float
    surrogate_bp: float


class VerifyReport(BaseModel):
    rows:              list[VerifyRow]
    rmse_calib_bp:     float
    rmse_surrogate_bp: float


class CalibrateResponse(BaseModel):
    theta_star:     Params
    cost:           float
    success:        bool
    message:        str
    model_version:  int               # ← which registry version served this
    verify:         VerifyReport


# =============================================================================
# /price
# =============================================================================
class PriceRequest(BaseModel):
    params:      Params
    instruments: list[Instrument] = Field(..., min_length=1)


class PriceResponse(BaseModel):
    ivs:           list[float]
    model_version: int


# =============================================================================
# /models, /models/{name}/promote
# =============================================================================
class ModelVersion(BaseModel):
    version:    int
    aliases:    list[str]
    created_at: datetime
    run_id:     str | None = None


class ModelsListResponse(BaseModel):
    name:     str
    versions: list[ModelVersion]


class PromoteRequest(BaseModel):
    version: int = Field(..., ge=1, examples=[1])
    alias:   str = Field(
        ...,
        min_length=1,
        pattern=r"^[a-z][a-z0-9_-]*$",
        examples=["production"],
    )


class PromoteResponse(BaseModel):
    name:    str
    version: int
    alias:   str
    note:    str = (
        "Alias updated in the registry. The running API still serves the "
        "PREVIOUSLY-loaded model — restart the service to pick up the new "
        "alias target."
    )
